In [ ]:
# Install all the packages

install.packages("tidyverse")
install.packages("lubridate")
install.packages("skimr")

library(tidyverse)
library(lubridate)
library(ggplot2)
library(dplyr)
library(skimr)

Then each cyclistic file would be loaded into the R database. I used the .csv files from September, 2021 until August, 2022.



Sep21 <- read.csv("202109-divvy-tripdata.csv")
Oct21 <- read.csv("202110-divvy-tripdata.csv")
Nov21 <- read.csv("202111-divvy-tripdata.csv")
Dec21 <- read.csv("202112-divvy-tripdata.csv")
Jan22 <- read.csv("202201-divvy-tripdata.csv")
Feb22 <- read.csv("202202-divvy-tripdata.csv")
Mar22 <- read.csv("202203-divvy-tripdata.csv")
Apr22 <- read.csv("202204-divvy-tripdata.csv")
May22 <- read.csv("202205-divvy-tripdata.csv")
Jun22 <- read.csv("202206-divvy-tripdata.csv")
Jul22 <- read.csv("202207-divvy-tripdata.csv")
Aug22 <- read.csv("202208-divvy-tripdata.csv")

In [ ]:
# Combine all files into one file called "totaltripdata"

totaltripdata <- rbind(Sep21,Oct21,Nov21,Dec21,Jan22,Feb22,Mar22,Apr22,May22,Jun22,Jul22,Aug22)

In [ ]:
nrow(totaltripdata) # number of rows
[1] 5883043

ncol(totaltripdata) # number of columns
[1] 13

head(totaltripdata) # check the first 6 rows of the data frame

         ride_id rideable_type          started_at            ended_at start_station_name start_station_id
1 9DC7B962304CBFD8 electric_bike 2021-09-28 16:07:10 2021-09-28 16:09:54                                    
2 F930E2C6872D6B32 electric_bike 2021-09-28 14:24:51 2021-09-28 14:40:05                                    
3 6EF72137900BB910 electric_bike 2021-09-28 00:20:16 2021-09-28 00:23:57                                    
4 78D1DE133B3DBF55 electric_bike 2021-09-28 14:51:17 2021-09-28 15:00:06                                    
5 E03D4ACDCAEF6E00 electric_bike 2021-09-28 09:53:12 2021-09-28 10:03:44                                    
6 346DE323A2677DC0 electric_bike 2021-09-28 01:53:18 2021-09-28 02:00:02                                    
end_station_name end_station_id start_lat start_lng end_lat end_lng member_casual       date month day year
1                                     41.89    -87.68   41.89  -87.67        casual 2021-09-28    09  28   21
2                                     41.94    -87.64   41.98  -87.67        casual 2021-09-28    09  28   21
3                                     41.81    -87.72   41.80  -87.72        casual 2021-09-28    09  28   21
4                                     41.80    -87.72   41.81  -87.72        casual 2021-09-28    09  28   21
5                                     41.88    -87.74   41.88  -87.71        casual 2021-09-28    09  28   21
6                                     41.87    -87.75   41.88  -87.74        casual 2021-09-28    09  28   21
day_of_week ride_length
1           2         164
2           2         914
3           2         221
4           2         529
5           2         632
6           2         404

tail(totaltripdata) # check the last 6 rows of the data frame

    ride_id rideable_type          started_at            ended_at           start_station_name
5883038 3A50755D869397FB electric_bike 2022-08-09 06:41:21 2022-08-09 06:45:22 Ashland Ave & Wellington Ave
5883039 EC17BE8AB1D73C88 electric_bike 2022-08-12 08:28:26 2022-08-12 08:42:26    Paulina St & Montrose Ave
5883040 57BAC0EA3A067A83 electric_bike 2022-08-22 12:30:19 2022-08-22 12:36:32     California Ave & 21st St
5883041 9B97FAE30276C299 electric_bike 2022-08-09 07:43:31 2022-08-09 07:50:50 Clinton St & Washington Blvd
5883042 2B4A9BA1E9AA9B51 electric_bike 2022-08-24 14:31:58 2022-08-24 14:40:32 Ashland Ave & Wellington Ave
5883043 7F0D048AC7C3B81A electric_bike 2022-08-24 09:45:04 2022-08-24 09:45:19       Clark St & Lincoln Ave
        start_station_id end_station_name end_station_id start_lat start_lng end_lat end_lng member_casual       date
5883038            13269                                  41.93610 -87.66984   41.94  -87.68        member 2022-08-09
5883039     TA1309000021                                  41.96156 -87.67143   41.94  -87.64        member 2022-08-12
5883040            13096                                  41.85375 -87.69581   41.84  -87.69        member 2022-08-22
5883041           WL-012                                  41.88340 -87.64122   41.89  -87.66        member 2022-08-09
5883042            13269                                  41.93608 -87.66990   41.93  -87.64        member 2022-08-24
5883043            13179                                  41.91578 -87.63468   41.92  -87.63        member 2022-08-24
        month day year day_of_week ride_length
5883038    08  09   22           2         241
5883039    08  12   22           5         840
5883040    08  22   22           1         373
5883041    08  09   22           2         439
5883042    08  24   22           3         514
5883043    08  24   22           3          15

summary(totaltripdata) # statistical summary of the data 

 ride_id          rideable_type       started_at          ended_at         start_station_name start_station_id  
 Length:5883043     Length:5883043     Length:5883043     Length:5883043     Length:5883043     Length:5883043    
 Class :character   Class :character   Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                                                                  
                                                                                                                  
                                                                                                                  
                                                                                                                  
 end_station_name   end_station_id       start_lat       start_lng         end_lat         end_lng      
 Length:5883043     Length:5883043     Min.   :41.64   Min.   :-87.84   Min.   :41.39   Min.   :-88.97  
 Class :character   Class :character   1st Qu.:41.88   1st Qu.:-87.66   1st Qu.:41.88   1st Qu.:-87.66  
 Mode  :character   Mode  :character   Median :41.90   Median :-87.64   Median :41.90   Median :-87.64  
                                       Mean   :41.90   Mean   :-87.65   Mean   :41.90   Mean   :-87.65  
                                       3rd Qu.:41.93   3rd Qu.:-87.63   3rd Qu.:41.93   3rd Qu.:-87.63  
                                       Max.   :45.64   Max.   :-73.80   Max.   :42.37   Max.   :-87.50  
                                                                        NA's   :5727    NA's   :5727    
 member_casual           date               month               day                year           day_of_week       
 Length:5883043     Min.   :2021-09-01   Length:5883043     Length:5883043     Length:5883043     Length:5883043    
 Class :character   1st Qu.:2021-11-06   Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Median :2022-05-07   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                    Mean   :2022-03-21                                                                              
                    3rd Qu.:2022-07-06                                                                              
                    Max.   :2022-08-31                                                                              
                                                                                                                    
  ride_length     
 Min.   :  -8245  
 1st Qu.:    363  
 Median :    643  
 Mean   :   1185  
 3rd Qu.:   1160  
 Max.   :2442301  

colnames(totaltripdata) # list of column names

[1] "ride_id"            "rideable_type"      "started_at"         "ended_at"           "start_station_name"
[6] "start_station_id"   "end_station_name"   "end_station_id"     "start_lat"          "start_lng"         
[11] "end_lat"            "end_lng"            "member_casual"  

sum(is.na(totaltripdata)) # check how many rows are NA
[1] 11454

totaltripdata <- na.omit(totaltripdata) # Drop all NA rows

summary(totaltripdata) # Check the summary of data

dim(totaltripdata) # dimension of the dataset

colnames(totaltripdata) # check column name of the dataset

str(totaltripdata) # Check the column data type 

summary(totaltripdata) # Check the summary of the dataset

skim(totaltripdata) # Check the summary of the data, see if any data missing

Transform the date into day of week, day, month and year

In [ ]:
totaltripdata$date <- as.Date(totaltripdata$started_at)
totaltripdata$month <- format(as.Date(totaltripdata$date), "%m")
totaltripdata$day <- format(as.Date(totaltripdata$date), "%d")
totaltripdata$year <- format(as.Date(totaltripdata$date), "%y")
totaltripdata$day_of_week <- format(as.Date(totaltripdata$date), "%w")

# Calculate the time difference between ended_at and started_at, add a new column called ride_length
totaltripdata$ride_length <- difftime(totaltripdata$ended_at, totaltripdata$started_at)

is.factor(totaltripdata$ride_length)
[1] FALSE

totaltripdata$ride_length <- as.numeric(as.character(totaltripdata$ride_length))

is.numeric(totaltripdata$ride_length)
[1] TRUE

skim(totaltripdata$ride_length)

# Set up a new dataset called "totaltripdata_2" including the ride_length greater than 0
totaltripdata_2 <- totaltripdata[!(totaltripdata$ride_length<0),] 

skim(totaltripdata_2)

Aggregate the totaltripdata_2

In [ ]:
aggregate(totaltripdata_2$ride_length ~ totaltripdata_2$member_casual, FUN = mean)

  totaltripdata_2$member_casual totaltripdata_2$ride_length
1                        casual                   1758.0228
2                        member                    771.3398

aggregate(totaltripdata_2$ride_length ~ totaltripdata_2$member_casual, FUN = median)

  totaltripdata_2$member_casual totaltripdata_2$ride_length
1                        casual                         835
2                        member                         538

aggregate(totaltripdata_2$ride_length ~ totaltripdata_2$member_casual, FUN = max)
 
  totaltripdata_2$member_casual totaltripdata_2$ride_length
1                        casual                     2442301
2                        member                       89998

aggregate(totaltripdata_2$ride_length ~ totaltripdata_2$member_casual, FUN = min)

  totaltripdata_2$member_casual totaltripdata_2$ride_length
1                        casual                           0
2                        member                           0

Order the days of the week, set Sunday as the first day of the week

In [ ]:
totaltripdata_2$day_of_week <- ordered(totaltripdata_2$day_of_week, levels=c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"))

In [ ]:
# Plot the numnber_of_rides vs. day of week
totaltripdata_2 %>% 
  mutate(weekday = wday(started_at, label = TRUE)) %>% 
  group_by(member_casual, weekday) %>% 
  summarise(number_of_rides = n(), average_duration = mean(ride_length)) %>% 
  arrange(member_casual, weekday) %>% 
  ggplot(aes(x = weekday, y = number_of_rides, fill = member_casual)) + geom_col(position = "dodge")

In [ ]:
# Plot the average duration of rides vs. day of week
totaltripdata_2 %>% 
  mutate(weekday = wday(started_at, label = TRUE)) %>% 
  group_by(member_casual, weekday) %>% 
  summarise(number_of_rides = n(), average_duration = mean(ride_length)) %>%
  arrange(member_casual, weekday)  %>% 
  ggplot(aes(x = weekday, y = average_duration, fill = member_casual)) + geom_col(position = 'dodge')